### ISSUE TITLE
Make PHP-SQLLint available on packagist.org

### ISSUE THREAD

**Issue by echernyavskiy** [cweiske/php-sqllint#1]
Any chance `php-sqllint` could be made available through packagist.org please?

**Comment by cweiske** [comment]
Done: https://packagist.org/packages/cweiske/php-sqllint

**Comment by shadiakiki1986** [comment]
Hello
The github link on the packagist reference above is `git://git.cweiske.de/php-sqllint.git`
Is that a different repository than the github one?

It caused an error in my `composer require --dev cweiske/php-sqllint` command

```
  [Composer\Downloader\TransportException]                                               
  Your configuration does not allow connection to git://git.cweiske.de/php-sqllint.git.  
   See https://getcomposer.org/doc/06-config.md#secure-http for details.                 
```

so I added the following sections manually to my `composer.json` file t o fix it

```
...
    "repositories": [
      { "url": "https://github.com/cweiske/php-sqllint",
        "type": "git"
      } 
    ],
...
    "require-dev": {
...
        "cweiske/php-sqllint": "^0.1.1"
    },  
```

**Comment by cweiske** [comment]
This is my own git server; this repository here on github is only a mirror.

I don't know why composer doesn't allow to install you from git by default.
