### ISSUE TITLE
INSERT .. (SELECT ...) fails due to parenthsis

### ISSUE THREAD

**Issue by Unisolve** [cweiske/php-sqllint#12]
This sample MySQL statement is flagged as a syntax error:

INSERT IGNORE INTO user_role (member_id, role_id) (SELECT id, '4150C5' FROM mem WHERE mem_type='Full' AND email NOT LIKE '%example.com');

If I remove the parenthesis, it's no longer considered an error, ie: 

INSERT IGNORE INTO user_role (member_id, role_id) SELECT id, '4150C5' FROM mem WHERE mem_type='Full' AND email NOT LIKE '%example.com';

I hope this is helpful. php-sqllint is a great tool.

Edit: I now see that I should probably have raised this ticket at /phpmyadmin/sql-parser

**Comment by cweiske** [comment]
Yes, that should be in sql-parser.

I think this is already there, but for UPDATE (which probably is the same basic issue): https://github.com/phpmyadmin/sql-parser/issues/159

**Comment by cweiske** [comment]
Ah, you opened https://github.com/phpmyadmin/sql-parser/issues/163
