### ISSUE TITLE
Fails with a correct statement

### ISSUE THREAD

**Issue by oacevedo** [cweiske/php-sqllint#19]
```
ALTER TABLE tableName
ALTER `ColumnName` SET DEFAULT '';
```
With the previous correct statement, I'm getting the next error:

Checking SQL syntax of test.sql  Line 25, col 17 at "SET": A new statement was found, but no delimiter between it and the previous one.

**Comment by cweiske** [comment]
See the README:

> Does php-sqllint not detect a syntax error, or doesn't support a certain SQL statement? Then please report a bug at phpmyadmin/sql-parser.
