### ISSUE TITLE
Support linting sql files in a directory

### ISSUE THREAD

**Issue by aszenz** [cweiske/php-sqllint#20]
Thanks for building this tool, is there a way to lint all the `.sql` files in a directory.
I was hoping to use this in our ci pipeline like this 
`./vendor/bin/php-sqllint sql/` # where sql is a directory containing multiple sql files

**Comment by cweiske** [comment]
You can already pass multiple file names:

```
$ php-sqllint file1.sql file2.sql
```

Passing directories is not supported at the moment.

**Comment by aszenz** [comment]
Thank you for the information, I have updated the title and description to reflect this

**Comment by cweiske** [comment]
Patches welcome.
