### ISSUE TITLE
Missing comma in SELECT not detected

### ISSUE THREAD

**Issue by shadiakiki1986** [cweiske/php-sqllint#3]
I would've expected the following case to be an error in my query
`echo "select a b from c" | php-sqllint -`
but `php-sqllint` doesn't capture it

(as opposed to `echo "select a, b from c" | php-sqllint -` which should be ok)

I see that there already is a test case for missing commas in `CREATE` statements: [tests/files/create-missingcomma.sql](https://github.com/cweiske/php-sqllint/blob/master/tests/files/create-missingcomma.sql)

**Notes**
1. this also goes undetected in the `phpmyadmin/sql-parser` package by using their `lint-query` tool: `lint-query --query "SELECT a b from c"`
2. the SELECT query without the comma fails on Sql Server. I didnt test on MySQL

**Comment by cweiske** [comment]
I can't do anything here; please report the bug at the sql parser repo.
